#!/webscripts/cgi-bin/cgilua.cgi

--[[
Copyright (c) 2016, Imagination Technologies Limited and/or its affiliated group companies
and/or licensors

All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted
provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this list of conditions
   and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice, this list of
   conditions and the following disclaimer in the documentation and/or other materials provided
   with the distribution.

3. Neither the name of the copyright holder nor the names of its contributors may be used to
   endorse or promote products derived from this software without specific prior written
   permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR
IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY
WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
--]]


STR_ADVANCED = "Advanced"
STR_ADVANCED_HEADING = "Use this page to enter your network configuration details manually."
STR_ADVANCED_PAGE_TITLE = "Caskeid device Advanced Setup"
STR_ADVANCED_SECTION_HEADING = "Use the advanced settings if your network is hidden or you require a static IP address for your Caskeid device."
STR_AVAILABLE_NETWORKS = "Select your network"
STR_BANNER_TXT = "Get the Caskeid app from the Apple App Store (iOS) or Google Play (Android)"
STR_BASIC = "Basic"
STR_BACK = "Back"
STR_BACK_MSG = "Press %sBack%s to return to the previous page"
STR_BACK_HOME_MSG = "Press %sBack%s to return to the Home page"
STR_CHANGE_NAME = "Change name"
STR_CLEAR_SETTINGS = "Clear network settings"
STR_CLEAR_SETTINGS_MSG = "This will disconnect Caskeid device from your network and device will lose all saved network settings. Click OK to continue."
STR_CLOSE = "Close"
STR_CONFIRM_NO_NETWORK = "No network selected.\nYou will not be able to stream to Caskeid device over Wi-Fi.\n\n'OK' to continue.\n'Cancel' to go back and select a network."
STR_CONNECT = "Connect"
STR_CONNECT_MSG_1 = "Your device will now attempt to connect to your network. If you have any problems, consult your owner's manual."
STR_CONNECT_MSG_2 = "Your device will now attempt to connect to your network. If the connection fails, please push the Wi-Fi button again and re-try."
STR_CURRENT_NETWORK = "Current network"
STR_DEVICE_NAME = "Give your Caskeid device a name"
STR_DEVICE_WIFI_MAC = "Device Wi-Fi MAC address"
STR_DHCP = "DHCP"
STR_DNS_SERVER = "DNS server"
STR_DONE = "Done"
STR_ENC_TYPE = "Encryption type"
STR_ERROR_PAGE_1 = "We can't find the page you were looking for."
STR_ERROR_PAGE_2 = "This might be because a link you followed was incorrect, you may have typed an incorrect address into your browser or the page may simply not exist anymore."
STR_ERROR_PAGE_3 = "Return to Caskeid device Setup"
STR_ERROR_PAGE_TITLE = "Page Not Found"
STR_E500_PAGE_MSG = "If this fails, turn your Caskeid device off and on again before retrying. If you still cannot connect, try using a different browser."
STR_E500_PAGE_TITLE = "Sorry, something has gone wrong"
STR_E500_PAGE_TRY_AGAIN = "Try again"
STR_ETHERNET_MAC = "Ethernet MAC address"
STR_ETH_ADAPTER_NC_MSG = "USB to Ethernet adapter is not connected"
STR_BT_MAC = "Bluetooth MAC address:"
STR_BT_ADAPTER_NC_MSG = "Bluetooth adapter is not connected"
STR_HOME = "Home"
STR_HOME_PAGE_TITLE = "Set up your device"
STR_INVALID_DEVICE_NAME_MSG = "Please enter a name. Names can contain spaces but not accented characters or some symbols.\n\n"
STR_INVALID_DEVICE_NAME_MSG_2 = "Your Caskeid device name contains invalid characters. Names can contain spaces but not accented characters or some symbols.\n\n"
STR_INVALID_IP_SETTINGS_MSG = "IP address settings should be entered in the form xxx.xxx.xxx.xxx, where xxx is any number between 0 and 255."
STR_INVALID_NETWORK_NAME_MSG_1 = "Please enter a name.\n\n"
STR_INVALID_NETWORK_NAME_MSG_2 = "Your network name contains invalid characters.  Names can contain spaces but not accented characters and some symbols.\n\n"
STR_INVALID_PASSWORD_WEP_MSG = "This doesn't look like a valid password, please check and re-enter.\n\n"
STR_INVALID_PASSWORD_WPA_MSG = "This doesn't look like a valid password, please check and re-enter.\n\n"
STR_IP_ADDRESS = "IP address"
STR_IP_SETUP = "IP setting"
STR_JAVASCRIPT_MSG_1 = "JavaScript is required for some parts of the Caskeid device setup process."
STR_JAVASCRIPT_MSG_2 = "Some features may be disabled. Please enable JavaScript then refresh this page."
STR_JAVASCRIPT_MSG_3 = "JavaScript is required for device setup."
STR_JAVASCRIPT_NETWORK_LIST_MSG = "Please enable JavaScript to see the list of available networks."
STR_LANGUAGE = "Language"
STR_MAIN_HEADING = "Review the settings below and %sSave%s when you have finished."
STR_NETMASK = "Netmask"
STR_NETWORK_LIST_ERROR_MSG = "There was a problem loading the available networks list."
STR_NETWORK_NAME = "Network name"
STR_NONE = "None"
STR_NO_NETWORK = "You have not selected a Wi-Fi network. When you close Caskeid device Setup Manager, your device power light will light solid green to indicate that it is ready."
STR_NO_NETWORK_NOTE_1 = "If you want to connect Caskeid device to your Wi-Fi network later on, simply reconnect your setup device to Caskeid device Setup Manager and select your network from the list."
STR_NO_NETWORK_NOTE_2 = "After pressing Close, your setup device will disconnect from Caskeid device Setup Manager. If your browser displays an error message, close your browser and open the Caskeid app."
STR_NOTE = "Note"
STR_NOTES = "Notes"
STR_OPEN = "Open"
STR_PASSWORD = "Enter network password"
STR_PASSWORD_ADVANCED = "Network password"
STR_PASSWORD_HINT_MSG = "Please enter a password."
STR_PASSWORD_HINT_MSG_1 = "No password required"
STR_PASSWORD_HINT_MSG_2 = "Enter network password"
STR_SHOW_PASSWORD = "Show password"
STR_PRINTABLE_ASCII_MSG = ""
STR_REFRESH = "Refresh"
STR_ROUTER_IP = "Router IP"
STR_SAVE = "Save"
STR_SCANNING = "Scanning for networks"
STR_SELECT_ENCRYPTION = "Please select type"
STR_SELECT_NETWORK = "Select network"
STR_SELECTED_NETWORK = "Selected Wi-Fi network:"
STR_SETUP_COMPLETE = "Finalizing setup"
STR_SETUP_COMPLETE_CONGRATS = "Congratulations!"
STR_SETUP_COMPLETE_MSG_1 = "Please wait for some time for the device to connect to the network."
STR_SETUP_COMPLETE_MSG_2 = "Taking too long to connect. %sGet some help.%s"
STR_SETUP_COMPLETE_MSG_3 = "You will now be re-directed to the Caskeid app."
STR_SETUP_COMPLETE_HELP_MSG_1 = "The device might have failed to connect to your Wi-Fi network. This can happen if:"
STR_SETUP_COMPLETE_HELP_MSG_2 = "you mistyped your password"
STR_SETUP_COMPLETE_HELP_MSG_3 = "you selected the wrong network by mistake"
STR_SETUP_COMPLETE_HELP_MSG_4 = "your Caskeid device has been taken out of range of your network"
STR_SETUP_COMPLETE_HELP_MSG_5 = "To retry connection, follow the steps below:"
STR_SOFTWARE_VERSION = "Software version"
STR_SPKR_ORIENTATION = "Which way round would you like to use your Caskeid device?"
STR_SPKR_ORIENT_TYPE_HORIZ = "Landscape"
STR_ORIENT_TYPE_VERT_DESK = "Portrait"
STR_ORIENT_TYPE_VERT_WALL = "Portrait (wall-mounted)"
STR_STATIC_IP = "Static IP"
STR_WEP = "WEP"
STR_WPA_WPA2 = "WPA/WPA2"
STR_NOT_CONNECTED = "Not connected"
STR_CONN_ERR_NETWORK_NOT_FOUND = "network not found"
STR_CONN_ERR_AUTH_TIMED_OUT = "authentication attempt timed out"
STR_CONN_ERR_INVALID_NETWORK_PWD = "invalid network password"
STR_CONN_ERR_DYNAMIC_IP_FAILED = "dynamic IP assignment failed"
STR_CONN_ERR_STATIC_IP_FAILED = "static IP assignment failed"
STR_CONN_ERR_INVALID_NETWORK_CONFIGURED = "invalid network configured"
STR_CONN_ERR_WPS_AUTH_FAILED = "WPS authentication failed"
STR_CONN_ERR_NO_WPS_AP_FOUND = "no WPS-enabled access point found"
STR_CONN_ERR_WPS_PBC_FAILED = "WPS Push Button Configuration failed"
STR_CONN_ERR_WPS_AUTH_TIMED_OUT = "WPS authentication timed out"
STR_CONN_ERR_WPS_PBC_CANCELLED = "WPS Push Button Configuration cancelled"
STR_CONN_ERR_CONNECTION_CANCELLED = "network connection cancelled"
STR_CONN_ERR_NO_NETWORK_CONFIGURED = "no network configured"
STR_CONN_ERR_CONNECTION_DROPPED = "network connection dropped"
STR_ENABLE_BTMR = "Bluetooth Caskeid"
STR_BTMR_DESCRIPTION = "All devices with this switched on will play in sync when you send audio to one via Bluetooth."
STR_ENABLE_BT_DISCOVERABLE = "Bluetooth discoverable"
STR_BT_DISCOVERABLE_DESCRIPTION = "Switch on Bluetooth discoverable to make your Caskeid-enabled device visible to all Bluetooth compatible devices."
STR_SETUP_COMPLETE_NO_NETWORK = "Setup complete, no network selected"
STR_SETUP_COMPLETE_NO_NETWORK_MSG_1 = "You will not be able to stream to Caskeid device over Wi-Fi using the Caskeid app or use Bluetooth Caskeid."
STR_SETUP_COMPLETE_NO_NETWORK_MSG_2 = "You can stream to a single Caskeid device using Bluetooth."
STR_SETUP_COMPLETE_NO_NETWORK_MSG_3 = "Wi-Fi is required for audio playback across multiple speakers."
STR_SETUP_COMPLETE_NO_NETWORK_MSG_4 = "Changed your mind and want to connect Caskeid device to a network? %sGet some help.%s"
STR_SETUP_HELP_NO_NETWORK_MSG_1 = "To connect Caskeid device to your network, follow the steps below:"
STR_SETUP_HELP_NO_NETWORK_MSG_2 = "Make sure Caskeid device is in range of your Wi-Fi network."
STR_SETUP_HELP_NO_NETWORK_MSG_3 = "Briefly press Caskeid device's %sWi-Fi%s button. Device's Power light will start flashing %sgreen%s."
STR_SETUP_HELP_NO_NETWORK_MSG_4 = "From your setup device (i.e. the device you are reading this on), reselect Caskeid device's wireless network."
STR_SETUP_HELP_NO_NETWORK_MSG_5 = "Open your browser to the Caskeid device setup page."
STR_SETUP_HELP_NO_NETWORK_MSG_6 = "Carefully enter your Wi-Fi network details and %sSave%s."
STR_SETUP_HELP_NO_NETWORK_MSG_7 = "Caskeid device's Power light should be flashing %sgreen%s. If not, briefly press Caskied device's %sWi-Fi%s button."
STR_SETUP_COMPLETE_APP_HINT_MSG_1 = "Using an Apple or Android device?"
STR_SETUP_COMPLETE_APP_HINT_MSG_2 = "We recommend you use the Caskeid app to set up your device."
STR_SETUP_COMPLETE_APP_HINT_MSG_3 = "Get it from the Apple App store (iOS) or Google Play (Android):"
STR_SETUP_COMPLETE_APP_HINT_MSG_4 = "If you need further help, visit our %sSupport Site%s"
STR_DISABLE_WIFI = "Disable Wi-Fi"
STR_DISABLE_WIFI_MSG = "This will temporarily turn off Caskeid device's Wi-Fi.\nTo re-enable Wi-Fi turn Caskeid device fully off and on again.\nClick OK to turn off Wi-Fi now."
STR_BT_VISIBLE = "On (discoverable)"
STR_BT_HIDDEN = "On (hidden)"
STR_BT_OFF = "Off"

STR_CI40_DEVICE_NAME = "Device name"
STR_DEVICE_DESC = "Description"
STR_DEVICE_REG_CODE = "Registration code"
STR_REGISTER_CI40_TITLE = "Register your Ci40"
STR_INVALID_DEVICE_REG_CODE_MSG = "Please enter a registration code.\n\n"
STR_REGISTER = "Register"
STR_REGISTER_CI40_MSG = "To manage your devices via FlowCloud register them with your account by retrieving a registration code from the web site and then entering it below. You can also identify your device by giving it a name and description."
STR_GATEWAY_NAME_PLACEHOLDER = "Gateway Name"
STR_GATEWAY_DESCRIPTION_PLACEHOLDER = "Device description"
STR_PENDING_REGISTRATION = "Pending registration"
STR_REGISTERED_TO_FM2M = "Registered to FlowM2M"
STR_CONSTRAINED_DEVICE_NAME_PLACEHOLDER = "Device"
STR_CONSTRAINED_DEVICE_TYPE_PLACEHOLDER = "Constrained device type"
STR_REGISTER_DEVICE_BUTTON = "Register"
STR_DELETE_DEVICE_BUTTON = "Delete"
STR_PROVISION_SUCCESS = "Provision is successful"
STR_PROVISION_FAIL = "Provision failed"
STR_ALREADY_PROVISIONED = "Device is already provisioned"
STR_UBUS_CONNECTION_FAIL = "Ubus connection failed"
STR_UBUS_TIMEOUT = "Ubus timeout"
